source ~/dotfiles/.vimrc.colors
source ~/dotfiles/.vimrc.basic
source ~/dotfiles/.vimrc.apperance
source ~/dotfiles/.vimrc.bundle
source ~/dotfiles/.vimrc.editing
source ~/dotfiles/.vimrc.unite
source ~/dotfiles/.vimrc.syntastic
source ~/dotfiles/.vimrc.completion.neocomplete
source ~/dotfiles/.vimrc.completion.neosnippet
