[[plugins]]
repo =  'Konfekt/FastFold'

[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo =  'Shougo/deoplete.nvim'

[[plugins]]
repo =  'ujihisa/neco-look'

[[plugins]]
repo =  'pocke/neco-gh-issues'

[[plugins]]
repo =  'Shougo/neco-syntax'

[[plugins]]
repo =  'Shougo/neosnippet'

[[plugins]]
repo =  'Shougo/neosnippet-snippets'

[[plugins]]
repo =  'tpope/vim-rails'

[[plugins]]
repo =  'kana/vim-fakeclip'

[[plugins]]
repo =  'vim-ruby/vim-ruby'

[[plugins]]
repo =  'Source-Explorer-srcexpl.vim'

[[plugins]]
repo =  'taglist.vim'

[[plugins]]
repo =  'tpope/vim-endwise'

[[plugins]]
repo =  'scrooloose/nerdtree'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'taku-o/vim-toggle'

[[plugins]]
repo = 'smartword'

[[plugins]]
repo = 'matchit.zip'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'haml.zip'

[[plugins]]
repo = 'digitaltoad/vim-jade'

[[plugins]]
repo = 'jQuery'

[[plugins]]
repo = 'nginx.vim'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'tpope/vim-markdown'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'digitaltoad/vim-jade'

[[plugins]]
repo = 'isRuslan/vim-es6'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'vim-jp/vim-go-extra'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo =  'Shougo/neomru.vim'

[[plugins]]
repo =  'Shougo/unite.vim'

[[plugins]]
repo =  'tsukkee/unite-help'

[[plugins]]
repo =  'h1mesuke/unite-outline'

[[plugins]]
repo =  'basyura/unite-rails'

[[plugins]]
repo =  'thinca/vim-unite-history'

[[plugins]]
repo =  'tsukkee/unite-tag'

[[plugins]]
repo =  'tpope/vim-fugitive'

[[plugins]]
repo =  'Lokaltog/vim-powerline'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
