"let $NVIM_TUI_ENABLE_TRUE_COLOR=1
source ~/dotfiles/nvim/vimrc.dein
source ~/dotfiles/nvim/vimrc.colors
source ~/dotfiles/nvim/vimrc.basic
source ~/dotfiles/nvim/vimrc.appearance
source ~/dotfiles/nvim/vimrc.editing
source ~/dotfiles/nvim/vimrc.unite
source ~/dotfiles/nvim/vimrc.syntastic
source ~/dotfiles/nvim/vimrc.deoplete
"source ~/dotfiles/nvim/vimrc.completion.neocomplete
source ~/dotfiles/nvim/vimrc.completion.neosnippet
source ~/dotfiles/nvim/vimrc.vimgo
